services:
  - type: web
    name: sanisidro-backend
    env: java
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/sanisidro-backend-1.0.0.jar
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m -Xms256m
      - key: SPRING_PROFILES_ACTIVE
        value: prod
